ProyectoDjango1/ProyectoDjango1/urls.py
from django.conf.urls import include
from django.contrib import admin

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views


from django.contrib.auth.views import login, logout_then_login

#configuracion de media
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
##################3

from django.views.generic.base import RedirectView
from allauth.account.views import *


urlpatterns = [
	#1.8.1 circulos
	url(r'^zonas/$', app.views.Zonas, name="zonas"),
	#1.6 FIltros
    url(r'^filtro/([0-9]*)/$', app.views.Filtro, name='filtro'),
	url(r'insertar/', app.views.insertar, name='insertar'),
    url(r'contador/', app.views.contador.as_view(), name='contador'),
    # Examples:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^$',RedirectView.as_view(url='accounts/login/')),
	url(r'^denuncia/$', app.views.Denuncia, name='denuncia_view'),
	url(r'^accounts/', include('allauth.urls')),
	url(r'^mapa/$',app.views.Mapa.as_view(),name='mapa_view'),
	url(r'^comments/',include('django_comments.urls')),
	url(r'^noticia/(?P<pk>\d+)/$', app.views.Noticia, name='noticia_view'),
	url(r'^perfil/(?P<pk>\d+)/$',app.views.Perfil,name='perfil_view'),
	url(r'^perfiluser/$',app.views.PerfilUser,name='perfilUser_view'),
	url(r'^actualizar/(?P<pk>\d+)/$',app.views.UpdatePerfil.as_view(),name='actualizarPerfil_view'),
#	url(r'^registrar/$',app.views.RegisterPerfil.as_view(),name='registrarPerfil_view'), 
	#url(r'^registrarperfil_view/(?P<pk>\d+)/$',app.views.RegisterPerfil.as_view(),name='registrarPerfil_view'), 



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoDjango1/app/models.py
"""
Definition of models.
"""

from django.db import models

from django.contrib.auth.models import User


class Usuario_m(models.Model):
	Nombre = models.OneToOneField(User,on_delete=models.CASCADE)
	Telefono = models.IntegerField(null=True, blank=True)
	Direccion = models.CharField(max_length=100,null=True, blank=True)
	Avatar = models.FileField(upload_to='avatar/%Y/%m/%d', null=True, blank=True)

	def __unicode__(self):
		return self.Nombre.username



 
class Denuncia_m(models.Model):
	user=models.ForeignKey(User)
	titulo=models.CharField(max_length=50)
	descripcion=models.TextField()
	latitud=models.FloatField()
	longitud=models.FloatField()
	lista_categorias=(
        (1,'Reten'),
		(2,'Bache'),
		(3,'Accidente'),
		(4,'Reparaciones'),
		(5,'Evento'),
		(6,'Otro')
        )
	categoria=models.IntegerField(choices=lista_categorias, verbose_name=u"Categoria",null=True, blank=True)
	lista_nivel=(
		(1,'Totalmente bloqueado'),
		(2,'Parcialmente bloqueado'),
		(3,'Ninguno')
		)
	nivel=models.IntegerField(choices=lista_nivel, verbose_name=u"Nivel",null=True, blank=True)
	 #1.6.1 Votos y rangos
	estado=models.NullBooleanField(verbose_name=u"Activado",null=True, blank=True)
    #1.7 Reportes
	fecha=models.DateTimeField(auto_now=True)
	reportado=models.NullBooleanField(verbose_name=u"Reportado",null=True, blank=True)
	
	def __unicode__(self):
		return self.titulo

class imagenes_m(models.Model):
	denunciaA=models.ForeignKey(Denuncia_m, null=True, blank=True)
	imagen=models.FileField(upload_to='img/%Y/%m/%d',null=True, blank=True)
	
	def __unicode__(self):
		return self.denunciaA.user.username

class videos_m(models.Model):
    denunciaB=models.ForeignKey(Denuncia_m, null=True, blank=True)
    video=models.FileField(upload_to='img/%Y/%m/%d',null=True, blank=True)
    
    def __unicode__(self):
			return self.denunciaB.user.username
	
class Comentario_m(models.Model):
	user=models.ForeignKey(User)
	denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
	comentario=models.CharField(max_length=250)
	
	def __unicode__(self):
		return self.comentario

#1.6.1 Likes, rangos y reportados
class Rango_m(models.Model):
	usuario=models.ForeignKey(User,null=True, blank=True)
	buenos=models.IntegerField(null=True, blank=True)
	malos=models.IntegerField(null=True, blank=True)
	#1.7 Reportes
	fecha=models.DateTimeField(auto_now=True)
class Favor_m(models.Model):
	usuario=models.ForeignKey(User,null=True, blank=True)
	denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
	#1.7 Reportes
	fecha=models.DateTimeField(auto_now=True)
class Contra_m(models.Model):
	usuario=models.ForeignKey(User,null=True, blank=True)
	denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
	#1.7 Reportes
	fecha=models.DateTimeField(auto_now=True)
class Reportados_m(models.Model):
    usuario=models.ForeignKey(User,null=True, blank=True)
    denuncia=models.ForeignKey(Denuncia_m,null=True, blank=True)
    #1.7 Reportes
    fecha=models.DateTimeField(auto_now=True)
#Fin 1.6.1

#1.8.1 Circulos
class Circulos_m(models.Model):
	x=models.FloatField(null=True, blank=True)
	y=models.FloatField(null=True, blank=True)
	cantidad=models.IntegerField(null=True, blank=True)
	fecha=models.DateField(auto_now=True)
#Fin 1.8.1

ProyectoDjango1/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *

class Usuario_Form(UserCreationForm):
		Telefono = forms.IntegerField()
		Direccion = forms.CharField(max_length =100)
		Avatar = forms.FileField()
 

class imagenes_f(forms.ModelForm):
    class Meta:
        model=imagenes_m
        fields=['imagen']
class videos_f(forms.ModelForm):
    class Meta:
        model=videos_m
        fields=['video']

class Denuncia_Form(forms.ModelForm):
	class Meta:
		model=Denuncia_m
		fields = [
			'user',
			'titulo',
			'descripcion',
			'latitud',
			'longitud',
			'categoria',
			'nivel'
		
			
		]

		labels={
			'user':'Usuario',
			'titulo':'Titulo',
			'descripcion':'Descripcion',
			'latitud':'Latitud',
			'longitud':'Longitud',
			'categoria':'Categoria',
			'nivel':'Nivel'
			
			
		}

		widgets={
			'titulo':forms.TextInput(attrs={'id':'nombre'}),
			'latitud':forms.TextInput(attrs={'id':'lat'}),
			'longitud':forms.TextInput(attrs={'id':'lng'}),
		}

class Comentario_form(forms.ModelForm):
	class Meta:
		model=Comentario_m
		fields=[
			'user',
			'denuncia',
			'comentario'
		]
		
#1.6.1 Likes,rangos...
class Favor_f(forms.ModelForm):
    class Meta:
        model=Favor_m
        fields='__all__'
class Contra_f(forms.ModelForm):
    class Meta:
        model=Contra_m
        fields='__all__'
#fin 1.6.1
#1.6.3 Reportes
class Reportados_f(forms.ModelForm):
	class Meta:
		model=Reportados_m
		fields='__all__'
#Fin 1.6.3

ProyectoDjango1/app/templates/app/actualizar.html
{% extends "app/base.html" %}


{% block content %}

<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col">
			<form method="POST" class="form-control" enctype="multipart/form-data">
				{% csrf_token %}
				 {{ form.as_p }}
				 <input type="submit" value="Actualizar">
				 <input type="reset" value="Cancel">
			</form>	
		</div>
	</div>
</div>

{% endblock content %}

ProyectoDjango1/app/templates/app/base.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}Document {% endblock titulo %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
	{% block estilos %}
		<style>
				.foot{
					height: 50px;
					display: flex;
					align-items: center;
					justify-content: center;
					color: white;
					background: #34495e !important;

				}

				.cabecera{
					background: #34495e !important;
				}
		</style>
	{% endblock estilos %}
	
	{% block extra %}
		
	{% endblock extra %}
		
 
</head>

<body>
	{% block menu %}
		<div class="container">
			<div class="row">
				<div class="col">
					<nav class="navbar navbar-dark bg-primary navbar-expand-md fixed-top cabecera" id="mainNav">
						<div class="container">
							<a class="navbar-brand js-scroll-trigger" href="/">
									</a>
							<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
								<span class="navbar-toggler-icon"></span>
							</button>
							<div class="collapse navbar-collapse" id="navbarResponsive">
								<ul class="navbar-nav ml-auto text-center">
									<li class="nav-item">
										<a class="nav-link js-scroll-trigger" href="{% url 'mapa_view'%}">Mapa</a>
									</li>
									<li class="nav-item">
										<a class="nav-link js-scroll-trigger" href="{% url 'denuncia_view'%}">Crear Denuncia</a>
									</li>
									<li class="nav-item">
										<a class="nav-link js-scroll-trigger" href="{% url 'perfilUser_view' %} ">Perfil</a>
									</li>
									<li class="nav-item">
										<form action="{% url 'account_logout'%}" method="POST">
											{% csrf_token %}
											<a href="#" class="nav-link js-scroll-trigger" onclick="$(this).closest('form').submit()">Salir</a>
										</form>
									</li> 
								</ul>
							</div>
						</div>
					</nav>
			</div>
		</div>
	</div>
	{% endblock menu %}
{% block content %}

{% endblock %}
	

{% block footer %}
<div class="mt-5 pt-5"></div>
	<footer class="container-fluid bg-primary d-flex foot fixed-bottom">
		<div class="row align-items-center">
			<div class="col  ">
				Huerta Cuevas Javier 
			</div>
		</div>
	</footer>
{% endblock footer %}
	
    

    <script src="{% static 'app/scripts/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'app/scripts/popper.min.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

ProyectoDjango1/app/templates/app/contador.html
{% extends "app/base.html" %}


{% block content %}

{% for x in object_list %}
    <p>{{ forloop.counter + 10 }}</p>
{%endfor%}
{% endblock content %}

ProyectoDjango1/app/templates/app/denuncia_respaldo.html
{% extends "app/base.html" %}



{% block content %}
<!--
<div id="map">  </div>
<div class='map-overlay top'>
    <div class='map-overlay-inner'>
      

        <div class="container mt-5 pt-5 mb-5 pb-5">
            <div class="row">
                <div class="col">

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %} 
                        


                        <input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

                        <p><label for="nombre">Titulo:</label> <input type="text" name="titulo" required="" id="nombre" maxlength="50"></p>
                        <p><label for="id_descripcion">Descripcion:</label> <textarea name="descripcion" id="id_descripcion" rows="10" cols="40" required=""></textarea></p>
                        <input type="hidden" name="latitud" required="" id="lat">
                        <input type="hidden" name="longitud" required="" id="lng">
                        <p><label for="id_img">Imagen:</label> <input type="file" name="img" required="" id="id_img"></p>
                        <p><label for="id_video">Video:</label> <input type="file" name="video" id="id_video"></p>

                        <br>

                        <br>

                        <input type="submit" value="Registrar" onclick="obtenerCoordenadas()">
                        <input type="reset" value="Cancelar">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
-->
<div class="container mt-5 pt-5">
	<div class="col">
		<div class="row">
			<form method = "POST">
				{% csrf_token %}  
				{{form2.as_p}}
			
				<br>

				<input type ="submit" value = "Registrar">
				<input type ="reset" value = "Cancelar">	
			</form>
				
		</div>
	</div>
</div>
<script>

    // Note: This example requires that you consent to location sharing when
    // prompted by your browser. If you see the error "The Geolocation service
    // failed.", it means you probably did not give permission for the browser to
    // locate you.
    var marker;
    var x = 0;
    var y = 0;
    function initMap() {



        var map = new google.maps.Map(document.getElementById('map'), {
            center: { lng: -117.034670, lat: 32.514981 },
            zoom: 13


        });


        // Try HTML5 geolocation.
        if (navigator.geolocation) {

            navigator.geolocation.getCurrentPosition(function (position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                /*
                var infoWindow = new google.maps.InfoWindow({map: map});
              infoWindow.setPosition(pos);
              infoWindow.setContent('Tu estas aqui.');
              map.setCenter(pos);
                */
                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lng: pos.lng, lat: pos.lat }
                });
                map.setCenter(pos);


            }, function () {

                marker = new google.maps.Marker({
                    map: map,
                    draggable: true,
                    animation: google.maps.Animation.DROP,
                    position: { lng: -117.034670, lat: 32.514981 }
                });
                //handleLocationError(true, infoWindow, map.getCenter());

                });

        } else {

            marker = new google.maps.Marker({
                map: map,
                draggable: true,
                animation: google.maps.Animation.DROP,
                position: { lng: -117.034670, lat: 32.514981 }
            });
            // Browser doesn't support Geolocation
            //handleLocationError(false, infoWindow, map.getCenter());



        }
        marker.addListener('click', function () {
            obtenerCoordenadas();
        });

    }
    /*
          function handleLocationError(browserHasGeolocation, infoWindow, pos) {
            infoWindow.setPosition(pos);
            infoWindow.setContent(browserHasGeolocation ?
                                  'Error: The Geolocation service failed.' :
                                  'Error: Your browser doesn\'t support geolocation.');
          }*/

    function obtenerCoordenadas() {
        var marcador_coords = marker.getPosition();
        x = marcador_coords.lng();
        y = marcador_coords.lat();
        document.getElementById("lat").value = y;
        document.getElementById("lng").value = x;
    }
    obtenerCoordenadas();
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1-teWu2BHQOmSdWhPxGi6K8eA2uCfUAg&callback=initMap">
</script>

<style>
    .map-overlay {
        font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
        position: absolute;
        width: 200px;
        top: 0;
        left: 0;
        padding: 10px;
    }

        .map-overlay .map-overlay-inner {
            background-color: #fff;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.10);
            border-radius: 3px;
            padding: 10px;
            margin-bottom: 10px;
        }

    .map-overlay-inner fieldset {
        border: none;
        padding: 0;
        margin: 0 0 10px;
    }

        .map-overlay-inner fieldset:last-child {
            margin: 0;
        }

    .map-overlay-inner select {
        width: 100%;
    }

    .map-overlay-inner label {
        display: block;
        font-weight: bold;
        margin: 0 0 5px;
    }

    .map-overlay-inner button {
        display: inline-block;
        width: 36px;
        height: 20px;
        border: none;
        cursor: pointer;
    }

        .map-overlay-inner button:focus {
            outline: none;
        }

        .map-overlay-inner button:hover {
            box-shadow: inset 0 0 0 3px rgba(0, 0, 0, 0.10);
        }
    /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
    #map {
        height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }

    #wrapper {
        position: relative;
    }

    #over_map {
        position: absolute;
        top: 10px;
        left: 10px;
        z-index: 99;
    }

    .right {
    }
</style>
{% endblock content %}
	

ProyectoDjango1/app/templates/app/index.html
{% extends "app/base.html" %}

ProyectoDjango1/app/templates/app/noticia.1_res.html
{% extends "app/base.html" %}

{% block estilos %}

<script src="https://use.fontawesome.com/a368244793.js"></script>


<style>

		.foot{
			height: 50px;
			display: flex;
			align-items: center;
			justify-content: center;
			color: white;
			background: #34495e !important;
		}
		.img{
			min-width: 100%;
			min-height: 200px;
			max-height: 400px;
			background: blanchedalmond;
		}

		.form_comentarios textarea {
			width: 100%;
			height: 84px;
			max-width: 100%;
			min-width: 100%;
			min-height: 84px;
			max-height: 300px;
			padding: 10px;
			font-family: 'Roboto', sans-serif;
			line-height: 30px;
			border: 1px solid #4b65d1;
			margin-bottom: 20px;
		}
		.cabecera{
			background: #34495e !important;
		}

		.perfil{
			margin-right: 10px;
		}

		.bot{
			min-width: 30px;
			min-height: 50px;
			
			margin: 0;
			border: 0;
			background: transparent;
			
			
		}

		.pt{
			font-size: 50px;
			
		}
		
</style>
{% endblock estilos %}


{% block content %}
{% load staticfiles %}

<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col-12 mt-3">
			<div class="carousel slide" id="principal-carousel" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#principal-carousel" data-slid-to="0" class="active"></li>
					<li data-target="#principal-carousel" data-slid-to="1"></li>
					<li data-target="#principal-carousel" data-slid-to="2"></li>
				</ol>


				<a href="#principal-carousel" class="carousel-control-prev" data-slide="prev">
					<span class="carousel-control-prev-icon" aria-hidden="true"></span>
					<span class="sr-only">Anterior</span>
				</a>

				<a href="#principal-carousel" class="carousel-control-next" data-slide="next">
					<span class="carousel-control-next-icon" aria-hidden="true"></span>
					<span class="sr-only">Siguiente</span>
				</a>
			</div>
		</div>
	</div>
</div>

{% for x in ctx %}
	<div class="container ">
		<div class="row">
			<div class="col-12 text-center mb-3 pb-3 h1">{{x.titulo}}</div>
				<div id="carouselExampleIndicators" class=" col-12 carousel slide" data-ride="carousel">
				<!--
					<ol class="carousel-indicators">
					  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
					  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
					  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
					</ol>
				-->
					<div class="carousel-inner">
						<!-- imagenes -->
						{% for y in ctx2 %}				
							{% if forloop.first %}
								<div class="carousel-item  active  ">
									<img class="d-block img img-fluid " src="{{y.imagen.url}}" alt="First slide">
								</div>
							{% else %}
								<div class="carousel-item ">
									<img class="d-block img img-fluid " src="{{y.imagen.url}}" alt="First slide">
								</div>
							{% endif %}
						
						{% endfor %}
		
						<!-- VIDEOS -->
						{% for z in ctx3 %}
						<div class="carousel-item">
							
							{% if z.video %}			
								<img class="d-block w-90 img img-fluid" src="{{z.video.url}}" alt="First slide">
							{% endif %}
								
						</div>
						{% endfor %}
		
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
					  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
					  <span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
					  <span class="carousel-control-next-icon" aria-hidden="true"></span>
					  <span class="sr-only">Next</span>
					</a>
				</div>


				<!--Inicia 1.6.2 Votos-->
			<div class="col-12 mt-5">
					<!--1.6.3 reputacion-->
					Reputaci&oacute;n: {{nivel}}%
					<!--Fin 1.6.3-->
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% if x == 1 or ninguno == False %}
						<!--
							<input type="submit" value="Contra" name="contra"/>
							<input type="submit" value="Favor" name="favor" />
						-->
							<button type="submit" value="Contra" name="contra" class="bot">
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot">
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>
							
						{% else %}
						{% if x == 2 or favor == True %}
						<!--
							<input type="submit" value="Contra" name="contra" />
							<input type="submit" value="Favor" name="favor" disabled/>
						-->
							<button type="submit" value="Contra" name="contra" class="bot">
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot" disabled>
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>
						{% endif %}
						{% if x == 3 or favor == False %}
						<!--
							<input type="submit" value="Contra" name="contra" disabled/>
							<input type="submit" value="Favor" name="favor" />
						-->
							<button type="submit" value="Contra" name="contra" class="bot" disabled>
									<i class="fa fa-thumbs-o-down pt" aria-hidden="true"></i>
							</button>

							<button type="submit" value="Favor" name="favor" class="bot">
									<i class="fa fa-thumbs-o-up pt" aria-hidden="true"></i>
							</button>

						{% endif %}
						{% endif %}
						
	
					</form>
					<!--Fin 1.6.2-->
					<!--Inicia 1.6.3 reportes-->
					Reportar
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% if reportado == True %}
						<input type="submit" value="Reportar" name="reportar" disabled />
						{% endif %}
						{% if reportado == False %}
						<input type="submit" value="Reportar" name="reportar" />
						{% endif %}
					</form>
	<!--Fin 1.6.3-->
			
			<div class="col-12 mt-5">
				<p class="h5">{{x.descripcion}}</p>
			</div>
			<div class="col-12 mt-5">
					<form method = "POST" class="form_comentarios d-flex justify-content-end flex-wrap">
						{% csrf_token %} 

						<input type="hidden" name="user" required="" id="id_user" value="{{user.id}}">

						<input type="hidden" name="denuncia" required="" id="id_denuncia" value="{{x.id}}">

						<textarea name="comentario" required id="id_comentario" maxlength="250" placeholder="Comentario"></textarea>
						
						<input type="submit" value="Comentar">
					</form>
				
			</div>
			<div class="col-12 mt-5 pb-5 mb-5">
					<h2>Comentarios</h2>
					
			
				{% for a in ctx5 %}
				<div class="media">
					
					{% if a.Avatar %}
					
						{% ifequal a.Avatar 'None' %}
							<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="300px" height="300px" alt="Imagen aleatoria">
						{% else %}
							<img class="perfil" src="{{a.Avatar.url}}" width="64px" height="64px"/>
						{% endifequal %}
						
				{% else %}
					<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="64px" height="64px" alt="Imagen aleatoria">
			
				{% endif %}
				
					<div class="media-body">
						<p class="nombre"><a href="{% url 'perfil_view' pk=a.Nombre_id %}">{{a.username}}</a></p>
						<p class="comentario">
							{{a.comentario}}
						</p>
						

					</div>
				</div>
				<hr>
				{% endfor %}		
			</div>
			
		</div>
	</div>

{% endfor%}


{% endblock content %}
	

ProyectoDjango1/app/templates/app/perfiluser.html
{% extends "app/base.html" %}
{% block estilos %}
{% load staticfiles %}
<style>
		.foot{
			height: 50px;
			display: flex;
			align-items: center;
			justify-content: center;
			color: white;
			background: #34495e !important;

		}

		.cabecera{
			background: #34495e !important;
		}
		.perfil{
			border-radius: 50%;
		}
</style>
{% endblock estilos %}

{% block content %}
<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col-6">
			<h1>Perfil usuario</h1>
			<p>Usuario {{user.username}}</p>
			
			
				
			
			{% if user.firts_name %}
				<p>Nombre {{user.firts_name}}</p>				
			{% endif %}
			
			{% if user.last_name %}
				<p>Apellido {{user.last_name}}</p>
			{% endif %}
					
			
			{% if user.email %}
				<p>Correo {{user.email}}</p>	
			{% endif %}
			{% for v in actualizar %}
				<a href="{% url 'actualizarPerfil_view' pk=v.id %}">Actualizar mis datos</a>
			{% endfor %}

			
			
			
								
		</div>
		<div class="col-6">
			
			{% for a in ctx %}
				{% if a.Avatar %}
					
					{% ifequal a.Avatar 'None' %}
						<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="300px" height="300px" alt="Imagen aleatoria">
					{% else %}
						<img class="perfil" src="{{a.Avatar.url}}" width="300px" height="300px"/>
					{% endifequal %}
						
		
				{% else %}
					<img class="perfil" src="{% static 'app/img/noavatar.png' %}" width="300px" height="300px" alt="Imagen aleatoria">
			
				{% endif %}

			{% endfor %}
				
		</div>
	</div>
</div>
{% endblock content %}
	

ProyectoDjango1/app/templates/app/registrar.html
{% extends "app/base.html" %}


{% block content %}

<div class="container mt-5 pt-5">
	<div class="row">
		<div class="col">
			<form method="POST" class="form-control" enctype="multipart/form-data">
				{% csrf_token %}
				 
				<p>
					<label for="id_Nombre">Nombre:</label> 
					<select name="Nombre" required id="id_Nombre" >
						<option value="1">{{user.username}}</option>
					</select>
				</p>
				  <p><label for="id_Telefono">Telefono:</label> <input type="number" name="Telefono" id="id_Telefono" /></p>

				  <p><label for="id_Direccion">Direccion:</label> <input type="text" name="Direccion" id="id_Direccion" maxlength="100" /></p>
				  
				  <p><label for="id_Avatar">Avatar:</label> <input type="file" name="Avatar" id="id_Avatar" /></p>

				 <input type="submit" value="Actualizar">
				 <input type="reset" value="Cancel">
			</form>	
		</div>
	</div>
</div>

{% endblock content %}